GET http://localhost:3001/reg/get
Content-Type: application/json

###

POST http://localhost:3001/reg/addUser
Content-Type: application/json

{
    "name": "String",
  "gender": "String",
  "hobby": ["jhsdfj", "sdfsdfsdkj", "sdfsd"],
  "course": "String",
  "email": "mahi@gmail.com",
  "password": "mahi",
  "percentage": 74
}

###


POST http://localhost:3001/reg/login
Content-Type: application/json

{
  "email": "String",
  "password": "String"
}